// Complete Presets Library
import { Preset, PipelineStage, NodeConnection } from './types';
import { LeadStatus } from '@/lib/validation';

// Default contact methods helper
const defaultContactMethods = [
  { id: 'email', type: 'email' as const, enabled: true, settings: { timing: 'immediate' as const, frequency: 'once' as const, maxPerDay: 3, followUpStyle: 'moderate' as const, tone: 'professional' as const, goal: 'nurturing' as const } },
  { id: 'phone', type: 'phone' as const, enabled: true, settings: { timing: 'delayed' as const, delay: 24, frequency: 'once' as const, maxPerDay: 2, followUpStyle: 'moderate' as const, tone: 'professional' as const, goal: 'relationship' as const } },
  { id: 'text', type: 'text' as const, enabled: false, settings: { timing: 'delayed' as const, delay: 1, frequency: 'once' as const, maxPerDay: 2, followUpStyle: 'gentle' as const, tone: 'friendly' as const, goal: 'nurturing' as const } },
];

// PERSONALITY TYPE PRESETS
export const PERSONALITY_PRESETS: Preset[] = [
  {
    id: 'analytical',
    name: 'Analytical Buyer',
    description: 'For detail-oriented leads who need data and comparisons before deciding',
    category: 'personality-types',
    icon: '📊',
    complexity: 'medium',
    tags: ['data-driven', 'research', 'comparison'],
    stages: [
      { id: 'inbox', label: 'New Inquiry', statusId: 'new' as LeadStatus, x: 8, y: 40, width: 240, height: 200, icon: '📥', contactMethods: defaultContactMethods },
      { id: 'research', label: 'Research Phase', statusId: 'working' as LeadStatus, x: 28, y: 25, width: 220, height: 180, icon: '🔍', contactMethods: defaultContactMethods },
      { id: 'comparison', label: 'Comparison', statusId: 'working' as LeadStatus, x: 28, y: 60, width: 220, height: 180, icon: '⚖️', contactMethods: defaultContactMethods },
      { id: 'data-review', label: 'Data Review', statusId: 'working' as LeadStatus, x: 50, y: 40, width: 240, height: 200, icon: '📈', contactMethods: defaultContactMethods },
      { id: 'decision', label: 'Decision Ready', statusId: 'approval' as LeadStatus, x: 72, y: 30, width: 200, height: 160, icon: '✅', contactMethods: defaultContactMethods },
      { id: 'more-info', label: 'Needs More Info', statusId: 'circle-back' as LeadStatus, x: 72, y: 60, width: 200, height: 140, icon: '❓', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'inbox', toStageId: 'research', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'inbox', toStageId: 'comparison', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'research', toStageId: 'data-review', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'comparison', toStageId: 'data-review', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'data-review', toStageId: 'decision', style: 'solid', animated: true, condition: { type: 'replied' } },
      { id: 'c6', fromStageId: 'data-review', toStageId: 'more-info', style: 'dashed', animated: false, condition: { type: 'no-response', value: 72 } },
    ],
  },
  {
    id: 'emotional',
    name: 'Emotional Buyer',
    description: 'For leads driven by feelings, experience, and personal connection',
    category: 'personality-types',
    icon: '💝',
    complexity: 'medium',
    tags: ['relationship', 'experience', 'feelings'],
    stages: [
      { id: 'first-touch', label: 'First Touch', statusId: 'new' as LeadStatus, x: 8, y: 40, width: 220, height: 180, icon: '👋', contactMethods: defaultContactMethods },
      { id: 'connect', label: 'Building Rapport', statusId: 'working' as LeadStatus, x: 28, y: 40, width: 240, height: 200, icon: '🤝', contactMethods: defaultContactMethods },
      { id: 'experience', label: 'Experience Focus', statusId: 'working' as LeadStatus, x: 50, y: 25, width: 220, height: 160, icon: '✨', contactMethods: defaultContactMethods },
      { id: 'testimonials', label: 'Social Proof', statusId: 'working' as LeadStatus, x: 50, y: 55, width: 220, height: 160, icon: '⭐', contactMethods: defaultContactMethods },
      { id: 'ready', label: 'Emotionally Ready', statusId: 'approval' as LeadStatus, x: 75, y: 40, width: 220, height: 180, icon: '💖', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'first-touch', toStageId: 'connect', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'connect', toStageId: 'experience', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'connect', toStageId: 'testimonials', style: 'dashed', animated: false },
      { id: 'c4', fromStageId: 'experience', toStageId: 'ready', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'testimonials', toStageId: 'ready', style: 'solid', animated: true },
    ],
  },
  {
    id: 'impulsive',
    name: 'Impulsive Buyer',
    description: 'For fast-moving leads ready to make quick decisions',
    category: 'personality-types',
    icon: '⚡',
    complexity: 'simple',
    tags: ['fast', 'urgent', 'quick-decision'],
    stages: [
      { id: 'hot-lead', label: 'Hot Lead', statusId: 'new' as LeadStatus, x: 15, y: 40, width: 260, height: 220, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'fast-track', label: 'Fast Track', statusId: 'working' as LeadStatus, x: 45, y: 40, width: 260, height: 220, icon: '🚀', contactMethods: defaultContactMethods },
      { id: 'close', label: 'Close Deal', statusId: 'approval' as LeadStatus, x: 75, y: 40, width: 240, height: 200, icon: '🎯', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'hot-lead', toStageId: 'fast-track', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'fast-track', toStageId: 'close', style: 'solid', animated: true },
    ],
  },
  {
    id: 'relationship',
    name: 'Relationship Builder',
    description: 'For leads who value long-term relationships and trust',
    category: 'personality-types',
    icon: '🤝',
    complexity: 'advanced',
    tags: ['trust', 'long-term', 'nurture'],
    stages: [
      { id: 'intro', label: 'Introduction', statusId: 'new' as LeadStatus, x: 5, y: 40, width: 200, height: 180, icon: '👋', contactMethods: defaultContactMethods },
      { id: 'trust', label: 'Trust Building', statusId: 'working' as LeadStatus, x: 22, y: 25, width: 200, height: 160, icon: '🛡️', contactMethods: defaultContactMethods },
      { id: 'education', label: 'Education', statusId: 'working' as LeadStatus, x: 22, y: 55, width: 200, height: 160, icon: '📚', contactMethods: defaultContactMethods },
      { id: 'consult', label: 'Consultation', statusId: 'working' as LeadStatus, x: 42, y: 40, width: 220, height: 180, icon: '💬', contactMethods: defaultContactMethods },
      { id: 'proposal', label: 'Proposal', statusId: 'working' as LeadStatus, x: 62, y: 40, width: 200, height: 160, icon: '📋', contactMethods: defaultContactMethods },
      { id: 'partner', label: 'Partner', statusId: 'approval' as LeadStatus, x: 82, y: 40, width: 180, height: 160, icon: '🎉', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'intro', toStageId: 'trust', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'intro', toStageId: 'education', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'trust', toStageId: 'consult', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'education', toStageId: 'consult', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'consult', toStageId: 'proposal', style: 'solid', animated: true },
      { id: 'c6', fromStageId: 'proposal', toStageId: 'partner', style: 'solid', animated: true },
    ],
  },
  {
    id: 'budget-conscious',
    name: 'Budget Conscious',
    description: 'For price-sensitive leads who need value justification',
    category: 'personality-types',
    icon: '💰',
    complexity: 'medium',
    tags: ['price', 'value', 'financing'],
    stages: [
      { id: 'inquiry', label: 'Price Inquiry', statusId: 'new' as LeadStatus, x: 8, y: 40, width: 220, height: 180, icon: '💵', contactMethods: defaultContactMethods },
      { id: 'value', label: 'Value Demo', statusId: 'working' as LeadStatus, x: 28, y: 25, width: 200, height: 160, icon: '💎', contactMethods: defaultContactMethods },
      { id: 'finance', label: 'Finance Options', statusId: 'working' as LeadStatus, x: 28, y: 55, width: 200, height: 160, icon: '🏦', contactMethods: defaultContactMethods },
      { id: 'negotiate', label: 'Negotiation', statusId: 'working' as LeadStatus, x: 50, y: 40, width: 220, height: 180, icon: '🤝', contactMethods: defaultContactMethods },
      { id: 'deal', label: 'Best Deal', statusId: 'approval' as LeadStatus, x: 75, y: 40, width: 200, height: 160, icon: '✅', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'inquiry', toStageId: 'value', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'inquiry', toStageId: 'finance', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'value', toStageId: 'negotiate', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'finance', toStageId: 'negotiate', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'negotiate', toStageId: 'deal', style: 'solid', animated: true },
    ],
  },
];

// AGENT COMMUNICATION STYLE PRESETS
export const AGENT_STYLE_PRESETS: Preset[] = [
  {
    id: 'professional',
    name: 'Professional',
    description: 'Formal, business-focused communication style',
    category: 'agent-styles',
    icon: '👔',
    complexity: 'medium',
    tags: ['formal', 'business', 'corporate'],
    stages: [
      { id: 'inquiry', label: 'Initial Inquiry', statusId: 'new' as LeadStatus, x: 10, y: 40, width: 240, height: 200, icon: '📧', contactMethods: defaultContactMethods },
      { id: 'qualify', label: 'Qualification', statusId: 'working' as LeadStatus, x: 35, y: 40, width: 240, height: 200, icon: '📋', contactMethods: defaultContactMethods },
      { id: 'present', label: 'Presentation', statusId: 'working' as LeadStatus, x: 60, y: 40, width: 240, height: 200, icon: '📊', contactMethods: defaultContactMethods },
      { id: 'close', label: 'Close', statusId: 'approval' as LeadStatus, x: 85, y: 40, width: 200, height: 180, icon: '✅', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'inquiry', toStageId: 'qualify', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'qualify', toStageId: 'present', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'present', toStageId: 'close', style: 'solid', animated: true },
    ],
  },
  {
    id: 'friendly',
    name: 'Friendly',
    description: 'Warm, approachable, and conversational style',
    category: 'agent-styles',
    icon: '😊',
    complexity: 'simple',
    tags: ['warm', 'casual', 'approachable'],
    stages: [
      { id: 'hello', label: 'Say Hello', statusId: 'new' as LeadStatus, x: 12, y: 40, width: 220, height: 180, icon: '👋', contactMethods: defaultContactMethods },
      { id: 'chat', label: 'Get to Know', statusId: 'working' as LeadStatus, x: 38, y: 40, width: 240, height: 200, icon: '💬', contactMethods: defaultContactMethods },
      { id: 'help', label: 'Help Out', statusId: 'working' as LeadStatus, x: 64, y: 40, width: 240, height: 200, icon: '🤗', contactMethods: defaultContactMethods },
      { id: 'happy', label: 'Happy Customer', statusId: 'approval' as LeadStatus, x: 88, y: 40, width: 180, height: 160, icon: '🎉', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'hello', toStageId: 'chat', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'chat', toStageId: 'help', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'help', toStageId: 'happy', style: 'solid', animated: true },
    ],
  },
  {
    id: 'consultative',
    name: 'Consultative',
    description: 'Expert advisor approach with deep problem-solving',
    category: 'agent-styles',
    icon: '🎯',
    complexity: 'advanced',
    tags: ['expert', 'advisor', 'solution'],
    stages: [
      { id: 'discover', label: 'Discovery', statusId: 'new' as LeadStatus, x: 5, y: 40, width: 200, height: 180, icon: '🔍', contactMethods: defaultContactMethods },
      { id: 'diagnose', label: 'Diagnosis', statusId: 'working' as LeadStatus, x: 22, y: 25, width: 200, height: 150, icon: '🩺', contactMethods: defaultContactMethods },
      { id: 'needs', label: 'Needs Analysis', statusId: 'working' as LeadStatus, x: 22, y: 55, width: 200, height: 150, icon: '📝', contactMethods: defaultContactMethods },
      { id: 'solution', label: 'Solution Design', statusId: 'working' as LeadStatus, x: 42, y: 40, width: 220, height: 180, icon: '💡', contactMethods: defaultContactMethods },
      { id: 'recommend', label: 'Recommendation', statusId: 'working' as LeadStatus, x: 62, y: 40, width: 200, height: 160, icon: '⭐', contactMethods: defaultContactMethods },
      { id: 'implement', label: 'Implementation', statusId: 'approval' as LeadStatus, x: 82, y: 40, width: 180, height: 160, icon: '🚀', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'discover', toStageId: 'diagnose', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'discover', toStageId: 'needs', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'diagnose', toStageId: 'solution', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'needs', toStageId: 'solution', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'solution', toStageId: 'recommend', style: 'solid', animated: true },
      { id: 'c6', fromStageId: 'recommend', toStageId: 'implement', style: 'solid', animated: true },
    ],
  },
  {
    id: 'high-energy',
    name: 'High Energy',
    description: 'Enthusiastic, exciting, fast-paced engagement',
    category: 'agent-styles',
    icon: '⚡',
    complexity: 'simple',
    tags: ['exciting', 'fast', 'energetic'],
    stages: [
      { id: 'spark', label: 'Spark Interest', statusId: 'new' as LeadStatus, x: 15, y: 40, width: 240, height: 200, icon: '✨', contactMethods: defaultContactMethods },
      { id: 'excite', label: 'Build Excitement', statusId: 'working' as LeadStatus, x: 45, y: 40, width: 260, height: 220, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'action', label: 'Action Time!', statusId: 'approval' as LeadStatus, x: 78, y: 40, width: 220, height: 180, icon: '🎯', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'spark', toStageId: 'excite', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'excite', toStageId: 'action', style: 'solid', animated: true },
    ],
  },
];

// PIPELINE PURPOSE PRESETS
export const PURPOSE_PRESETS: Preset[] = [
  {
    id: 'buying-funnel',
    name: 'Buying Funnel',
    description: 'Standard purchase pipeline for vehicle buyers',
    category: 'pipeline-purposes',
    icon: '🛒',
    complexity: 'medium',
    tags: ['purchase', 'buyer', 'acquisition'],
    stages: [
      { id: 'awareness', label: 'Awareness', statusId: 'new' as LeadStatus, x: 5, y: 40, width: 180, height: 160, icon: '👀', contactMethods: defaultContactMethods },
      { id: 'interest', label: 'Interest', statusId: 'working' as LeadStatus, x: 20, y: 40, width: 180, height: 160, icon: '💡', contactMethods: defaultContactMethods },
      { id: 'consideration', label: 'Consideration', statusId: 'working' as LeadStatus, x: 35, y: 40, width: 200, height: 180, icon: '🤔', contactMethods: defaultContactMethods },
      { id: 'intent', label: 'Intent', statusId: 'working' as LeadStatus, x: 52, y: 40, width: 180, height: 160, icon: '🎯', contactMethods: defaultContactMethods },
      { id: 'evaluation', label: 'Evaluation', statusId: 'working' as LeadStatus, x: 67, y: 40, width: 180, height: 160, icon: '⚖️', contactMethods: defaultContactMethods },
      { id: 'purchase', label: 'Purchase', statusId: 'approval' as LeadStatus, x: 84, y: 40, width: 180, height: 160, icon: '🎉', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'awareness', toStageId: 'interest', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'interest', toStageId: 'consideration', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'consideration', toStageId: 'intent', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'intent', toStageId: 'evaluation', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'evaluation', toStageId: 'purchase', style: 'solid', animated: true },
    ],
  },
  {
    id: 'cold-nurture',
    name: 'Cold Lead Nurturing',
    description: 'Long-term nurture for cold/dormant leads',
    category: 'pipeline-purposes',
    icon: '❄️',
    complexity: 'advanced',
    tags: ['cold', 'nurture', 'long-term'],
    stages: [
      { id: 'cold', label: 'Cold Lead', statusId: 'new' as LeadStatus, x: 5, y: 40, width: 180, height: 160, icon: '❄️', contactMethods: defaultContactMethods },
      { id: 'warm-touch', label: 'Warm Touch', statusId: 'working' as LeadStatus, x: 20, y: 25, width: 180, height: 140, icon: '📧', contactMethods: defaultContactMethods },
      { id: 'value-add', label: 'Value Add', statusId: 'working' as LeadStatus, x: 20, y: 55, width: 180, height: 140, icon: '🎁', contactMethods: defaultContactMethods },
      { id: 're-engage', label: 'Re-Engage', statusId: 'working' as LeadStatus, x: 38, y: 40, width: 200, height: 180, icon: '🔄', contactMethods: defaultContactMethods },
      { id: 'warming', label: 'Warming Up', statusId: 'working' as LeadStatus, x: 55, y: 40, width: 180, height: 160, icon: '☀️', contactMethods: defaultContactMethods },
      { id: 'hot', label: 'Hot Again', statusId: 'approval' as LeadStatus, x: 72, y: 40, width: 180, height: 160, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'dormant', label: 'Stay Dormant', statusId: 'dead' as LeadStatus, deadReason: 'not-ready', x: 88, y: 40, width: 160, height: 140, icon: '💤', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'cold', toStageId: 'warm-touch', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'cold', toStageId: 'value-add', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'warm-touch', toStageId: 're-engage', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'value-add', toStageId: 're-engage', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 're-engage', toStageId: 'warming', style: 'solid', animated: true, condition: { type: 'replied' } },
      { id: 'c6', fromStageId: 're-engage', toStageId: 'dormant', style: 'dashed', animated: false, condition: { type: 'no-response', value: 168 } },
      { id: 'c7', fromStageId: 'warming', toStageId: 'hot', style: 'solid', animated: true },
    ],
  },
  {
    id: 'hot-closing',
    name: 'Hot Lead Closing',
    description: 'Fast-track pipeline for ready-to-buy leads',
    category: 'pipeline-purposes',
    icon: '🔥',
    complexity: 'simple',
    tags: ['hot', 'closing', 'fast'],
    stages: [
      { id: 'hot-in', label: 'Hot Inbound', statusId: 'new' as LeadStatus, x: 12, y: 40, width: 240, height: 200, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'qualify', label: 'Quick Qualify', statusId: 'working' as LeadStatus, x: 38, y: 40, width: 240, height: 200, icon: '✅', contactMethods: defaultContactMethods },
      { id: 'present', label: 'Present & Close', statusId: 'working' as LeadStatus, x: 64, y: 40, width: 240, height: 200, icon: '🎯', contactMethods: defaultContactMethods },
      { id: 'won', label: 'Won!', statusId: 'approval' as LeadStatus, x: 88, y: 40, width: 180, height: 160, icon: '🏆', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'hot-in', toStageId: 'qualify', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'qualify', toStageId: 'present', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'present', toStageId: 'won', style: 'solid', animated: true },
    ],
  },
  {
    id: 're-engagement',
    name: 'Re-Engagement',
    description: 'Win back lost or inactive leads',
    category: 'pipeline-purposes',
    icon: '🔄',
    complexity: 'medium',
    tags: ['winback', 'lost', 'reactivate'],
    stages: [
      { id: 'lost-pool', label: 'Lost Lead Pool', statusId: 'dead' as LeadStatus, deadReason: 'lost-contact', x: 8, y: 40, width: 220, height: 180, icon: '📦', contactMethods: defaultContactMethods },
      { id: 'reach-out', label: 'Reach Out', statusId: 'working' as LeadStatus, x: 30, y: 25, width: 200, height: 150, icon: '📞', contactMethods: defaultContactMethods },
      { id: 'offer', label: 'Special Offer', statusId: 'working' as LeadStatus, x: 30, y: 55, width: 200, height: 150, icon: '🎁', contactMethods: defaultContactMethods },
      { id: 'interested', label: 'Interested Again', statusId: 'working' as LeadStatus, x: 52, y: 40, width: 220, height: 180, icon: '💡', contactMethods: defaultContactMethods },
      { id: 'converted', label: 'Converted!', statusId: 'approval' as LeadStatus, x: 75, y: 30, width: 180, height: 140, icon: '🎉', contactMethods: defaultContactMethods },
      { id: 'permanent-lost', label: 'Permanently Lost', statusId: 'dead' as LeadStatus, deadReason: 'not-interested', x: 75, y: 60, width: 180, height: 140, icon: '❌', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'lost-pool', toStageId: 'reach-out', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'lost-pool', toStageId: 'offer', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'reach-out', toStageId: 'interested', style: 'solid', animated: true, condition: { type: 'replied' } },
      { id: 'c4', fromStageId: 'offer', toStageId: 'interested', style: 'solid', animated: true, condition: { type: 'clicked' } },
      { id: 'c5', fromStageId: 'interested', toStageId: 'converted', style: 'solid', animated: true },
      { id: 'c6', fromStageId: 'interested', toStageId: 'permanent-lost', style: 'dashed', animated: false, condition: { type: 'no-response', value: 336 } },
    ],
  },
];

// COMPLEXITY LEVEL PRESETS
export const COMPLEXITY_PRESETS: Preset[] = [
  {
    id: 'simple-3stage',
    name: 'Simple 3-Stage',
    description: 'Basic linear pipeline for beginners',
    category: 'complexity-levels',
    subcategory: 'simple',
    icon: '📊',
    complexity: 'simple',
    tags: ['basic', 'beginner', 'linear'],
    stages: [
      { id: 'new', label: 'New', statusId: 'new' as LeadStatus, x: 18, y: 45, width: 280, height: 220, icon: '📥', contactMethods: defaultContactMethods },
      { id: 'working', label: 'Working', statusId: 'working' as LeadStatus, x: 50, y: 45, width: 280, height: 220, icon: '⚙️', contactMethods: defaultContactMethods },
      { id: 'done', label: 'Done', statusId: 'approval' as LeadStatus, x: 82, y: 45, width: 260, height: 200, icon: '✅', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'new', toStageId: 'working', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'working', toStageId: 'done', style: 'solid', animated: true },
    ],
  },
  {
    id: 'standard-5stage',
    name: 'Standard 5-Stage',
    description: 'Balanced pipeline with follow-ups',
    category: 'complexity-levels',
    subcategory: 'medium',
    icon: '📈',
    complexity: 'medium',
    tags: ['standard', 'balanced', 'follow-up'],
    stages: [
      { id: 'new', label: 'New Leads', statusId: 'new' as LeadStatus, x: 8, y: 45, width: 220, height: 180, icon: '📥', contactMethods: defaultContactMethods },
      { id: 'engaged', label: 'Engaged', statusId: 'working' as LeadStatus, x: 28, y: 25, width: 200, height: 150, icon: '💬', contactMethods: defaultContactMethods },
      { id: 'followup', label: 'Follow Up', statusId: 'circle-back' as LeadStatus, x: 28, y: 62, width: 200, height: 150, icon: '📞', contactMethods: defaultContactMethods },
      { id: 'approved', label: 'Approved', statusId: 'approval' as LeadStatus, x: 55, y: 45, width: 220, height: 180, icon: '✅', contactMethods: defaultContactMethods },
      { id: 'archive', label: 'Archive', statusId: 'dead' as LeadStatus, x: 82, y: 45, width: 180, height: 150, icon: '📦', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'new', toStageId: 'engaged', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'new', toStageId: 'followup', style: 'dashed', animated: false },
      { id: 'c3', fromStageId: 'engaged', toStageId: 'approved', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'followup', toStageId: 'engaged', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'approved', toStageId: 'archive', style: 'dashed', animated: false },
    ],
  },
  {
    id: 'advanced-8stage',
    name: 'Advanced 8-Stage',
    description: 'Full funnel with predictions & branching',
    category: 'complexity-levels',
    subcategory: 'advanced',
    icon: '🚀',
    complexity: 'advanced',
    tags: ['advanced', 'branching', 'predictions'],
    stages: [
      { id: 'inbox', label: 'Inbox', statusId: 'new' as LeadStatus, x: 5, y: 40, width: 180, height: 200, icon: '📥', contactMethods: defaultContactMethods },
      { id: 'hot', label: 'Hot Leads', statusId: 'working' as LeadStatus, x: 20, y: 18, width: 160, height: 130, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'warm', label: 'Warm Leads', statusId: 'working' as LeadStatus, x: 20, y: 45, width: 160, height: 130, icon: '☀️', contactMethods: defaultContactMethods },
      { id: 'cold', label: 'Cold Leads', statusId: 'circle-back' as LeadStatus, x: 20, y: 72, width: 160, height: 120, icon: '❄️', contactMethods: defaultContactMethods },
      { id: 'negotiating', label: 'Negotiating', statusId: 'working' as LeadStatus, x: 42, y: 32, width: 180, height: 150, icon: '🤝', contactMethods: defaultContactMethods },
      { id: 'closing', label: 'Closing', statusId: 'approval' as LeadStatus, x: 62, y: 32, width: 180, height: 150, icon: '🎯', contactMethods: defaultContactMethods },
      { id: 'won', label: 'Won', statusId: 'approval' as LeadStatus, x: 82, y: 22, width: 150, height: 120, icon: '🏆', contactMethods: defaultContactMethods },
      { id: 'lost', label: 'Lost', statusId: 'dead' as LeadStatus, x: 82, y: 55, width: 150, height: 120, icon: '❌', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'inbox', toStageId: 'hot', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'inbox', toStageId: 'warm', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'inbox', toStageId: 'cold', style: 'dashed', animated: false },
      { id: 'c4', fromStageId: 'hot', toStageId: 'negotiating', style: 'solid', animated: true },
      { id: 'c5', fromStageId: 'warm', toStageId: 'negotiating', style: 'solid', animated: true },
      { id: 'c6', fromStageId: 'cold', toStageId: 'warm', style: 'dashed', animated: false, condition: { type: 'replied' } },
      { id: 'c7', fromStageId: 'negotiating', toStageId: 'closing', style: 'solid', animated: true },
      { id: 'c8', fromStageId: 'closing', toStageId: 'won', style: 'solid', animated: true },
      { id: 'c9', fromStageId: 'closing', toStageId: 'lost', style: 'dashed', animated: false, condition: { type: 'no-response', value: 168 } },
    ],
  },
  {
    id: 'power-user',
    name: 'Power User',
    description: 'Maximum control with all features',
    category: 'complexity-levels',
    subcategory: 'power-user',
    icon: '⚡',
    complexity: 'power-user',
    tags: ['power', 'maximum', 'all-features'],
    stages: [
      { id: 'inbound', label: 'Inbound', statusId: 'new' as LeadStatus, x: 3, y: 35, width: 150, height: 180, icon: '📥', contactMethods: defaultContactMethods },
      { id: 'qualify', label: 'Qualify', statusId: 'working' as LeadStatus, x: 15, y: 15, width: 140, height: 110, icon: '✅', contactMethods: defaultContactMethods },
      { id: 'segment-a', label: 'Segment A', statusId: 'working' as LeadStatus, x: 15, y: 38, width: 140, height: 100, icon: '🅰️', contactMethods: defaultContactMethods },
      { id: 'segment-b', label: 'Segment B', statusId: 'working' as LeadStatus, x: 15, y: 58, width: 140, height: 100, icon: '🅱️', contactMethods: defaultContactMethods },
      { id: 'disqualify', label: 'Disqualify', statusId: 'dead' as LeadStatus, x: 15, y: 78, width: 140, height: 100, icon: '❌', contactMethods: defaultContactMethods },
      { id: 'nurture-a', label: 'Nurture A', statusId: 'working' as LeadStatus, x: 30, y: 22, width: 140, height: 100, icon: '🌱', contactMethods: defaultContactMethods },
      { id: 'nurture-b', label: 'Nurture B', statusId: 'working' as LeadStatus, x: 30, y: 48, width: 140, height: 100, icon: '🌿', contactMethods: defaultContactMethods },
      { id: 'hot-track', label: 'Hot Track', statusId: 'working' as LeadStatus, x: 45, y: 22, width: 150, height: 110, icon: '🔥', contactMethods: defaultContactMethods },
      { id: 'warm-track', label: 'Warm Track', statusId: 'working' as LeadStatus, x: 45, y: 48, width: 150, height: 110, icon: '☀️', contactMethods: defaultContactMethods },
      { id: 'cold-track', label: 'Cold Track', statusId: 'circle-back' as LeadStatus, x: 45, y: 72, width: 150, height: 100, icon: '❄️', contactMethods: defaultContactMethods },
      { id: 'negotiate', label: 'Negotiate', statusId: 'working' as LeadStatus, x: 62, y: 35, width: 160, height: 140, icon: '🤝', contactMethods: defaultContactMethods },
      { id: 'proposal', label: 'Proposal', statusId: 'working' as LeadStatus, x: 78, y: 35, width: 150, height: 130, icon: '📋', contactMethods: defaultContactMethods },
      { id: 'closed-won', label: 'Closed Won', statusId: 'approval' as LeadStatus, x: 92, y: 20, width: 130, height: 100, icon: '🏆', contactMethods: defaultContactMethods },
      { id: 'closed-lost', label: 'Closed Lost', statusId: 'dead' as LeadStatus, x: 92, y: 50, width: 130, height: 100, icon: '📦', contactMethods: defaultContactMethods },
    ],
    connections: [
      { id: 'c1', fromStageId: 'inbound', toStageId: 'qualify', style: 'solid', animated: true },
      { id: 'c2', fromStageId: 'qualify', toStageId: 'segment-a', style: 'solid', animated: true },
      { id: 'c3', fromStageId: 'qualify', toStageId: 'segment-b', style: 'solid', animated: true },
      { id: 'c4', fromStageId: 'qualify', toStageId: 'disqualify', style: 'dashed', animated: false },
      { id: 'c5', fromStageId: 'segment-a', toStageId: 'nurture-a', style: 'solid', animated: true },
      { id: 'c6', fromStageId: 'segment-b', toStageId: 'nurture-b', style: 'solid', animated: true },
      { id: 'c7', fromStageId: 'nurture-a', toStageId: 'hot-track', style: 'solid', animated: true },
      { id: 'c8', fromStageId: 'nurture-b', toStageId: 'warm-track', style: 'solid', animated: true },
      { id: 'c9', fromStageId: 'warm-track', toStageId: 'cold-track', style: 'dashed', animated: false, condition: { type: 'no-response', value: 72 } },
      { id: 'c10', fromStageId: 'hot-track', toStageId: 'negotiate', style: 'solid', animated: true },
      { id: 'c11', fromStageId: 'warm-track', toStageId: 'negotiate', style: 'solid', animated: true },
      { id: 'c12', fromStageId: 'cold-track', toStageId: 'warm-track', style: 'dashed', animated: false, condition: { type: 'replied' } },
      { id: 'c13', fromStageId: 'negotiate', toStageId: 'proposal', style: 'solid', animated: true },
      { id: 'c14', fromStageId: 'proposal', toStageId: 'closed-won', style: 'solid', animated: true },
      { id: 'c15', fromStageId: 'proposal', toStageId: 'closed-lost', style: 'dashed', animated: false, condition: { type: 'no-response', value: 168 } },
    ],
  },
];

// Export all presets combined
export const ALL_PRESETS: Preset[] = [
  ...PERSONALITY_PRESETS,
  ...AGENT_STYLE_PRESETS,
  ...PURPOSE_PRESETS,
  ...COMPLEXITY_PRESETS,
];

// Preset categories for UI
export const PRESET_CATEGORIES = [
  {
    id: 'personality-types',
    label: 'Lead Personalities',
    icon: '🧠',
    description: 'Match your approach to lead behavior',
  },
  {
    id: 'agent-styles',
    label: 'Agent Styles',
    icon: '💼',
    description: 'Communication approaches',
  },
  {
    id: 'pipeline-purposes',
    label: 'Pipeline Types',
    icon: '🎯',
    description: 'Goal-specific funnels',
  },
  {
    id: 'complexity-levels',
    label: 'Complexity',
    icon: '📊',
    description: 'Simple to power user',
  },
];

